### ISSUE TITLE
Unable to create a PR for the docs repo of Orion

### ISSUE THREAD

**Issue by SavvyOsive** [tailflow/laravel-orion-docs#11] opened 2021-01-09 09:22 UTC
Hi, I'm a beginner to this project and facing the following issue(s) while trying to submit a new PR for the documentation. When I create a pull request from my fork, I get the following error messages in the _Deploy_ section of the CI tool that has been integrated :

```
fatal: unable to access 'https://github.com/tailflow/laravel-orion-docs.git/': The requested URL returned error: 403
Error: Action failed with "The process '/usr/bin/git' failed with exit code 128"
```

Also, I have been unable to find a streamlined process for the contribution to this project for a beginner, please refer a link to me so I can know how to get started from the get go. 
Thanks.

**Comment by SavvyOsive** [comment] 2021-01-09 09:24
![Screenshot from 2021-01-09 14-45-01](https://user-images.githubusercontent.com/64489116/104088097-677ad600-528a-11eb-8536-89112c4f1b57.png)

Here I'm attaching a screenshot of the error I got.

**Comment by alexzarbn** [comment] 2021-01-10 06:32
Hi @SavvyOsive,

The issue is fixed in https://github.com/tailflow/laravel-orion-docs/commit/b8931231fe5ca45f76b5b064296cfbda95f2a38a.
As for the contribution guidelines, they are currently not available, but I plan to include them in the coming weeks.

**Closed by alexzarbn** 2021-01-10 06:32 UTC
